config/routes.rb
Rails.application.routes.draw do
  resources :cookie_monsters, only: [:index, :new, :create]
  delete '/cookie_monsters', to: 'cookie_monsters#destroy'

  resources :sessions, only: [:index, :new, :create]

  resources :users, only: [:index, :new, :create]
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true, uniqueness: { scope: :last_name }
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cookie_monsters_controller.rb
class CookieMonstersController < ApplicationController
  def index
    @cookies = cookies
  end

  def new
  end

  def create
    cookies[cookie_data[:key]] = cookie_data[:value]
    redirect_to cookie_monsters_path
  end

  def destroy
    cookies.delete(params[:key])
    redirect_to cookie_monsters_path
  end

  private

  def cookie_data
    params[:cookie]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @session = session
  end

  def new
  end

  def create
    session[session_data[:key]] = session_data[:value]
    redirect_to sessions_path
  end

  def destroy
    sessions.delete(params[:key])
    redirect_to sessions_path
  end

  private

  def session_data
    params[:session_data]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User successfully created"
      redirect_to users_path
    else
      flash[:errors] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookie_monsters/index.html.erb
<h1>Welcome, Cookie Monsters!</h1>

<h4>Here are your cookies:</h4>

<table class="table">
  <thead>
    <th>Key</th>
    <th>Value</th>
  </thead>
<% @cookies.each do |key, value| %>
  <tr>
    <td><%= link_to "Delete", cookie_monsters_path(key: key), method: :delete %></td>
    <td><%= key %></td>
    <td><%= value %></td>
  </tr>
<% end %>
</table>
<%= link_to "Set a Cookie", new_cookie_monster_path %>

app/views/cookie_monsters/new.html.erb
<%= form_for(:cookie, url: cookie_monsters_path) do |f| %>
  <%= f.label :key %>
  <%= f.text_field :key %> <br>
  <%= f.label :value %>
  <%= f.text_field :value %> <br>
  <%= f.submit "Create Cookie" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SessionsCookiesFlashes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h2>All Users</h2>

<% @users.each do |user| %>
  <p><%= user.first_name %> <%= user.last_name %></p>
<% end %>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= form_for(@user) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %> <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %> <br>
  <%= f.submit %>
<% end %>